### PR TITLE
Printing of Prometheus metrics by Grafana dashboard

### PR DESCRIPTION
**Pull request by Diss31**
In order to analyze and simplify access to the Prometheus metrics on the ChirpStack components (application server, network server and gateway bridge), we have exposed the metrics and printed them on a default Grafana dashboard (with room for improvement). You can see the provided Markdown for more technical details.

### CODE REVIEW

**Comment by blocknonip** [comment]
This seems really heavyweight, no?

**Comment by Diss31** [comment]
@blocknonip in which meaning ? in terms of size of image ?

**Comment by brocaar** [comment]
Although I do appreciate your work, I have decided to not merge this. With this repository I try to provide an easy way to get started with the project. The scope is that you are a `docker-compose up` away from a working ChirpStack setup :)

When moving to production, there are many things to consider, including monitoring. However adding this to this repository would mean:

* I have to keep maintaining these components and support questions about it as it comes bundled
* Users have to understand more components / could perceive that ChirpStack is complex to setup as it comes with components that are not required to get started

I hope you do understand this decision. Even when this is not merged, please do share your work with the community as it could be helpful for people who wish to setup Prometheus based monitoring.

**Comment by Diss31** [comment]
@brocaar Thank you for taking the time to explain your choice to us :) We are a group of French students and that was our first contribution to an opensource project so your enlightenment will help us to progress for the next ones ! 
And we will also follow your recommendations and open a topic on the ChirpStack's forum.

**Pull request closed without merging**
