### PR TITLE
Add dependencies for services in docker-compose.yml

### PR DESCRIPTION
**Pull request by nibbl**
Dependencies will solve problems with preterm requests to services, logs will be more clean

### CODE REVIEW

**Comment by bconway** [comment]
I agree with this change and do the same in all my Compose files as a best practice. It's worth noting that this only verifies that a container has been started, not that it is available and accepting connections. **However**, I think adding the necessary heartbeat checks to Postgres, etc would make this file needlessly busy, since it is intended to be a skeleton.

If @brocaar agrees with this change, can you also update the `-env` file as well?

**Comment by nibbl** [comment]
Okay, I will update also -env.yml and update PR

**Comment by nibbl** [comment]
Good, I will wait while @brocaar agree with this PR
Thanks for a quick answer

**Comment by brocaar** [comment]
Thanks @nibbl! :+1:

**Pull request merged**
