### PR TITLE
Swarm implementation

### PR DESCRIPTION
**Pull request by ivan28823**
add yml file for docker swarm deploy

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks @ivan28823 for your contribution. However, I'm not sure if this should be merged into this repository. The purpose of this repo is to provide an easy way to get started with ChirpStack using Docker Compose, mainly to show how all components are interconnected. E.g. an user should be a single command away to setup the full stack. I often use this for demonstrations as I can create and teardown a ChirpStack environment.

When merging a recipe for Docker Swarm, a logical next step would be to also provide recipes for Kubernetes in this repo. This adds a lot of additional complexity, which also needs to be maintained.

This is my opinion, I'm looking forward to feedback from others on this :)

**Comment by blocknonip** [comment]
Probably not surprising, I am in agreement with @brocaar. However, with proposals like this coming in more frequently (like that other Grafana one), perhaps something more organized than simply posting to the forum is warranted. A chirpstack-recipes repository, maybe?

**Comment by brocaar** [comment]
@blocknonip what if we keep these kind of recipes external repos, but collect links to these repos in the `README.md`? @ivan28823  would you be happy with such a solution?

**Comment by sophiekovalevsky** [comment]
I understand the point of @brocaar in not merging this change since eventually it will become another task to should be maintained which translates in time, a time that maybe he would want to focus in other priorities within the scope of the project. 

I would decant myself toward in maintaining the repo as it's and add external sources on the README as Orne says, I think in that way would be less time effort to maintain it and at the same time giving access to the community from official resources of other recipes that can be used within the stack.

**Comment by ivan28823** [comment]
Ok, I understand the point, maybe deployments options (swarm, k8s) should be in another repo...

**Pull request closed without merging**
